"use strict"

let strOne = "Bismillaahir_Rahmaanir_Raheem_"
//console.log(strOne.length);
let count = 10;
/*
function funcString(strOne)
{
    for(let letter of strOne)
    {
        if(letter == 'a' || letter == 'e'  || letter == 'i' || letter == 'o' || letter == 'u')
        count++;
    }
    console.log(count)
}

funcString(strOne);
*/


const result = (strOne)=> {
                    console.log(strOne)

                }
                result();
